import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { Inter,Montserrat} from 'next/font/google';
import Header from "../components/Header";


export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};
const inter = Montserrat( {subsets: ['latin']})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        <Header> </Header>
          {children}
           </body>
      </html>
    </ClerkProvider>
  );
}
